apiVersion: v1
kind: Pod
metadata: 
  name: my-app-pod
  labels: 
    app: my-app
    type: frontend
spec: 
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 8080
  - name: log_cont
    image: log_cont 