apiVersion: batch/v1bet1
kind: CronJob
metadata: 
  name: reporting-cron-job
spec: 
  schedule: "*/1 * * * * "
  jobTemplate:
    spec: 
      completions: 3 # the number of healthy pod to deploy
      parallelism: 3 # to deploy 3 pods with out checkin if they are healthy or not     it is optionel 
      template:
        spec: 
          containers: 
          - name: myapp
            image: nginx
            command: ["expr","3","+","5"]
          restartPolicy: Nerver # or always