apiVersion: v1
kind: Pod
metadata: 
  name: my-app-pod
  labels: 
    name: my-app
    type: frontend
spec:
  containers:
    - name: nginx
      image: nginx
      ports: 
        - containePort: 8080
      resources: 
        request: 
          memory: "1Gi"
          cpu: 1
        limits: 
          memory: "2Gi"
          cpu: 2