apiVersion: v1
kind: Pod
metadata: 
  name: my-app-pod
  labels: 
    name: my-app
    type: frontend
spec:
  containers:
    - name: nginx
      image: nginx
      ports: 
        - containePort: 8080
  affinity: 
    requiredDuringSchedulingIgnoredDuringExecution:   # preferedignored  requiredrequired
      nodeSelectorTerms:
      - matchExpressions:
        - key: size
          operator: In # or NotIn or Exists
          values:
          -  Large
          -  Medium

      