apiVersion: v1
kind: Pod
metadata: 
  name: my-app-pod
  labels: 
    name: my-app
    type: frontend
spec:
  containers:
    - name: nginx
      image: nginx
      ports: 
        - containePort: 8080
      tolerations:
        key: app 
        operator: "Equal"
        value: "blue"
        effect: "NoShedule"
#kubectl taint node node1 app=blue:NoSchedule