apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pvc_voll
spec:
  accesMode: 
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data
  # awsElasticBlockStore:   in case storage in aws 
        #   volumeID: volume-id
        #   fsType: ext4
  PersistentVolumeReclaimPolicy: Reatain #when a pvc is deleted to let it run but not bounded incase a new pvc is generated
                                 # Delete
                                 #Reycle