apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: myapp-depl
  labels:
    app: myapp-pod
    type: front-end
spec: 
  template: 
    metadata: 
      name: myapp-pod
      labels:
        app: myapp-pod
        type: front-end
    spec:
      containers: 
        - name: nginx
          image: nginx
  replicas: 4
  selector:
    matchLabels: 
      app: myapp-pod
      type: front-end 
  serviceName: mysql-h
  podManagementPolicy: parallel