apiVersion: v1
kind: Pod
metadata: 
  name: myapp
spec: 
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /opt
      name: datavolume
    Volumes:
    - name: datavolume
      hostPath: 
        path: /data
        type: Directory
        # awsElasticBlockStore:   in case storage in aws 
        #   volumeID: volume-id
        #   fsType: ext4