apiVersion: v1
kind: Pod
metadata: 
  name: my-app-pod
  labels: 
    name: my-app
    type: frontend
spec:
  containers:
    - name: nginx
      image: nginx
      ports: 
        - containePort: 8080
      readnessProbe: 
        httpGet:
          path: /api/ready
          port: 8080
        #tcpSocket: fortcp
          #port: 8080
        #exec  for commands
          #command:
          #-  cat
          #-  /api/isready   
        initialDelaySeconds: 10
        periodSeconds: 5
        failureThreshold: 8